=begin
#Nodeum API

## About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  

The version of the OpenAPI document: 2.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nodeum::TaskCallbacksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaskCallbacksApi' do
  before do
    # run before each test
    @api_instance = Nodeum::TaskCallbacksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaskCallbacksApi' do
    it 'should create an instance of TaskCallbacksApi' do
      expect(@api_instance).to be_instance_of(Nodeum::TaskCallbacksApi)
    end
  end

  # unit tests for create_task_callback
  # Creates a new task callback.
  # **API Key Scope**: task_callbacks / create
  # @param task_id Numeric ID or name of task. Task names are not unique, it&#39;s recommanded to use numeric ID.
  # @param task_callback_body 
  # @param [Hash] opts the optional parameters
  # @return [TaskCallback]
  describe 'create_task_callback test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for destroy_task_callback
  # Destroys a specific task callback.
  # **API Key Scope**: task_callbacks / destroy
  # @param task_id Numeric ID or name of task. Task names are not unique, it&#39;s recommanded to use numeric ID.
  # @param task_callback_id Numeric ID of task callback.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'destroy_task_callback test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for index_task_callbacks
  # Lists all task callbacks.
  # **API Key Scope**: task_callbacks / index
  # @param task_id Numeric ID or name of task. Task names are not unique, it&#39;s recommanded to use numeric ID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The number of items to display for pagination.
  # @option opts [Integer] :offset The number of items to skip for pagination.
  # @option opts [Array<String>] :sort_by Sort results by attribute.  Can sort on multiple attributes, separated by &#x60;|&#x60;. Order direction can be suffixing the attribute by either &#x60;:asc&#x60; (default) or &#x60;:desc&#x60;.
  # @option opts [String] :id Filter on id
  # @option opts [String] :type Filter on type
  # @option opts [String] :script Filter on task callback script
  # @return [TaskCallbackCollection]
  describe 'index_task_callbacks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_task_callback
  # Displays a specific task callback.
  # **API Key Scope**: task_callbacks / show
  # @param task_id Numeric ID or name of task. Task names are not unique, it&#39;s recommanded to use numeric ID.
  # @param task_callback_id Numeric ID of task callback.
  # @param [Hash] opts the optional parameters
  # @return [TaskCallback]
  describe 'show_task_callback test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_task_callback
  # Updates a specific task callback.
  # **API Key Scope**: task_callbacks / update
  # @param task_id Numeric ID or name of task. Task names are not unique, it&#39;s recommanded to use numeric ID.
  # @param task_callback_id Numeric ID of task callback.
  # @param task_callback_body 
  # @param [Hash] opts the optional parameters
  # @return [TaskCallback]
  describe 'update_task_callback test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
